import { ACTIONS_SIDEBAR_TYPES } from '../../ActionsSidebar/ActionsSidebar.types'

import { ACTION_STATUS_TYPES } from '@/constants/actions'

export const PENDING_ACTIONS_DROPDOWN_TYPES = {
  CURRENT_USER_ACTIONS: 'CURRENT_USER_ACTIONS',
  OTHERS_ACTIONS: 'OTHERS_ACTIONS',
}

export const STATUS_ACTION_MAP = {
  [ACTION_STATUS_TYPES.COMPLETED]: ACTIONS_SIDEBAR_TYPES.DONE,
  [ACTION_STATUS_TYPES.APPROVED]: ACTIONS_SIDEBAR_TYPES.APPROVED,
  [ACTION_STATUS_TYPES.EXECUTING]: ACTIONS_SIDEBAR_TYPES.EXECUTING,
  [ACTION_STATUS_TYPES.FAILED]: ACTIONS_SIDEBAR_TYPES.FAILED,
  [ACTION_STATUS_TYPES.DENIED]: ACTIONS_SIDEBAR_TYPES.DENIED,
}
