/**
 * Mock data entry point
 *
 * This file merges all mock data from separate JSON files.
 * Auto-generated by sanitizeMockdata.js --auto-split
 */

// Import mock data files
import alertsData from './alerts.json'
import baseData from './base.json'
import containersData from './containers.json'
import operationsData from './operations.json'

import type { UnknownRecord } from '@/app/utils/deviceUtils/types'

/**
 * Simple object merge utility
 * Merges multiple objects into one, with later objects overwriting earlier ones
 */
function mergeMockData(...sources: UnknownRecord[]): UnknownRecord {
  return Object.assign({} as UnknownRecord, ...sources)
}

// Merge all mock data
const mockdata = mergeMockData(
  baseData as UnknownRecord,
  containersData as UnknownRecord,
  operationsData as UnknownRecord,
  alertsData as UnknownRecord,
)

// Assign to global window object
window.__mockdata = mockdata

export default mockdata
