import { COLOR } from './colors'

export const MINER_LOCATIONS = {
  WORKSHOP_WAREHOUSE: 'workshop.warehouse',
  WORKSHOP_LAB: 'workshop.lab',
  SITE_WAREHOUSE: 'site.warehouse',
  SITE_LAB: 'site.lab',
  SITE_CONTAINER: 'site.container',
  DISPOSED: 'disposed',
  VENDOR: 'vendor',
  MINER_ROOM: 'miner.room',
  ACME_CONTAINER: 'acme.container',
  SCRAPPED: 'scrapped',
  UNKNOWN: 'unknown',
} as const

export type MinerLocation = (typeof MINER_LOCATIONS)[keyof typeof MINER_LOCATIONS]

export const MINER_LOCATION_NAMES: Record<string, string> = {
  [MINER_LOCATIONS.SITE_WAREHOUSE]: 'Site Warehouse',
  [MINER_LOCATIONS.SITE_LAB]: 'Site Lab',
  [MINER_LOCATIONS.MINER_ROOM]: 'Miner Room',
  [MINER_LOCATIONS.VENDOR]: 'Vendor',
  [MINER_LOCATIONS.ACME_CONTAINER]: 'ACME Container',
  [MINER_LOCATIONS.SCRAPPED]: 'Scrapped',
  [MINER_LOCATIONS.DISPOSED]: 'Disposed',
  [MINER_LOCATIONS.UNKNOWN]: 'Unknown',
}

export const MINER_REPAIR_LOCATIONS = new Set<string>([
  MINER_LOCATIONS.WORKSHOP_LAB,
  MINER_LOCATIONS.SITE_LAB,
])

export const MINER_LOCATION_BG_COLORS: Record<string, string> = {
  [MINER_LOCATIONS.WORKSHOP_WAREHOUSE]: `${COLOR.YELLOW}33`,
  [MINER_LOCATIONS.WORKSHOP_LAB]: `${COLOR.YELLOW}33`,
  [MINER_LOCATIONS.SITE_CONTAINER]: `${COLOR.LIGHT_BLUE}33`,
  [MINER_LOCATIONS.SITE_WAREHOUSE]: `${COLOR.LIGHT_BLUE}33`,
  [MINER_LOCATIONS.SITE_LAB]: `${COLOR.LIGHT_BLUE}33`,
  [MINER_LOCATIONS.MINER_ROOM]: `${COLOR.LIGHT_BLUE}33`,
  [MINER_LOCATIONS.ACME_CONTAINER]: `${COLOR.LIGHT_BLUE}33`,
  [MINER_LOCATIONS.VENDOR]: `${COLOR.DARK_GREEN}33`,
  [MINER_LOCATIONS.SCRAPPED]: `${COLOR.YELLOW}33`,
  [MINER_LOCATIONS.DISPOSED]: `${COLOR.BRICK_RED}33`,
  [MINER_LOCATIONS.UNKNOWN]: `${COLOR.BRICK_RED}33`,
}

export const MINER_LOCATION_BORDER_COLORS: Record<string, string> = {
  [MINER_LOCATIONS.SITE_CONTAINER]: COLOR.LIGHT_BLUE,
  [MINER_LOCATIONS.SITE_WAREHOUSE]: COLOR.LIGHT_BLUE,
  [MINER_LOCATIONS.SITE_LAB]: COLOR.LIGHT_BLUE,
  [MINER_LOCATIONS.MINER_ROOM]: COLOR.LIGHT_BLUE,
  [MINER_LOCATIONS.WORKSHOP_WAREHOUSE]: COLOR.YELLOW,
  [MINER_LOCATIONS.WORKSHOP_LAB]: COLOR.YELLOW,
  [MINER_LOCATIONS.ACME_CONTAINER]: COLOR.LIGHT_BLUE,
  [MINER_LOCATIONS.VENDOR]: COLOR.DARK_GREEN,
  [MINER_LOCATIONS.SCRAPPED]: COLOR.YELLOW,
  [MINER_LOCATIONS.DISPOSED]: COLOR.BRICK_RED,
  [MINER_LOCATIONS.UNKNOWN]: COLOR.BRICK_RED,
}
