import { createApi } from '@reduxjs/toolkit/query/react'

import { baseQuery } from './baseQuery'
import { API_TAG_TYPES, CACHE_CONFIG } from './constants'
import { createEndpoints } from './endpoints'

export const api = createApi({
  reducerPath: 'api',
  baseQuery: baseQuery,
  tagTypes: API_TAG_TYPES,
  // Performance optimization: Better cache management
  keepUnusedDataFor: CACHE_CONFIG.KEEP_UNUSED_DATA_FOR,
  refetchOnMountOrArgChange: CACHE_CONFIG.REFETCH_ON_MOUNT_OR_ARG_CHANGE,
  refetchOnFocus: CACHE_CONFIG.REFETCH_ON_FOCUS,
  refetchOnReconnect: CACHE_CONFIG.REFETCH_ON_RECONNECT,
  endpoints: createEndpoints,
})

export const {
  useGetUserinfoQuery,
  usePostTokenQuery,
  useGetTailLogQuery,
  useGetMultiTailLogQuery,
  useLazyGetTailLogQuery,
  useLazyGetMultiTailLogQuery,
  useGetTailLogRangeAggrQuery,
  useGetListThingsQuery,
  useLazyGetListThingsQuery,
  useGetActionsQuery,
  useLazyGetActionsQuery,
  useGetBatchActionsQuery,
  useGetActionQuery,
  useAddNewActionMutation,
  useAddNewBatchActionMutation,
  useVoteForActionMutation,
  useCancelActionsMutation,
  useAddThingCommentMutation,
  useEditThingCommentMutation,
  useDeleteThingCommentMutation,
  useGetListRacksQuery,
  useGetExtDataQuery,
  useLazyGetExtDataQuery,
  useGetGlobalDataQuery,
  usePostProductionDataMutation,
  useAddFeatureFlagsMutation,
  useGetSiteQuery,
  useGetGlobalConfigQuery,
  useGetHistoricalLogsQuery,
  useLazyGetHistoricalLogsQuery,
  useGetUsersQuery,
  useUpdateUserMutation,
  useDeleteUserMutation,
  useCreateUserMutation,
  useLazyGetUserPermissionsQuery,
  useGetWorkerConfigQuery,
  useGetThingConfigQuery,
  useGetSettingsQuery,
  useGetOperationsHashrateQuery,
  useGetRevenueQuery,
  useGetCostsQuery,
  useGetCostEnergyQuery,
  useGetCostProductionQuery,
  useGetDowntimeQuery,
  useGetDowntimeCurtailmentQuery,
  useGetDowntimeOperationalIssuesQuery,
  useGetOperationsWorkersQuery,
  useGetOperationsConsumptionQuery,
  useGetOperationsEfficiencyQuery,
  useUpdateSettingsMutation,
  useSetGlobalConfigMutation,
  useGetBtcDataCurrentQuery,
  useGetBtcDataPriceQuery,
  useGetBtcDataHashPriceQuery,
  useGetBtcDataHashrateQuery,
  useGetProductionCostsQuery,
  useGetCostOperationalEnergyQuery,
  useLazyGetProductionCostsQuery,
  useSetProductionCostsMutation,
  useSetSiteEnergyGlobalDataMutation,
  useSetContainerSettingsMutation,
  useGetContainerSettingsQuery,
  useLazyGetContainerSettingsQuery,
  useGetFeatureConfigQuery,
  useGetFeaturesQuery,
  useGetReportsQuery,
  useLazyGetReportsQuery,
} = api
